package com.zhang.mapper;

import com.zhang.entity.magnet_model;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;
@Mapper
public interface magnet_modelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table magnet_db
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    int insert(magnet_model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table magnet_db
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    int insertSelective(magnet_model record);

    List<magnet_model> selectAll();
    List<magnet_model> queryMagnetByConditions(Map<String,Object> map);

    int queryCountOfMagnet(Map<String,Object> map);

    String queryMagnetByNum(String num);

    List<String> queryMagnetsByNums(String[] nums);

    List<magnet_model> queryMagnetBySelectTypes(Map<String,Object> map);

    int queryPagesByTypes(Map<String, Object> map);
    List<String> selectAllTypes();
    void insertSelectedRow(String num);
    List<magnet_model> selectBytype(String type);

    List<String> haveUrlNum();



}