package com.zhang.entity;

import lombok.Data;
import org.springframework.boot.autoconfigure.domain.EntityScan;

@Data
public class magnet_model {
    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.title
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.actress
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String actress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.subline
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String subline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.HD
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String hd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.magnet
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String magnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.num
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.types
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.date
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String date;

    private String producer;

    public String getProducer() {
        return producer;
    }

    public void setProducer(String producer) {
        this.producer = producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_db.title
     *
     * @return the value of magnet_db.title
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_db.title
     *
     * @param title the value for magnet_db.title
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_db.actress
     *
     * @return the value of magnet_db.actress
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public String getActress() {
        return actress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_db.actress
     *
     * @param actress the value for magnet_db.actress
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public void setActress(String actress) {
        this.actress = actress == null ? null : actress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_db.subline
     *
     * @return the value of magnet_db.subline
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public String getSubline() {
        return subline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_db.subline
     *
     * @param subline the value for magnet_db.subline
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public void setSubline(String subline) {
        this.subline = subline == null ? null : subline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_db.HD
     *
     * @return the value of magnet_db.HD
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public String getHd() {
        return hd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_db.HD
     *
     * @param hd the value for magnet_db.HD
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public void setHd(String hd) {
        this.hd = hd == null ? null : hd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_db.magnet
     *
     * @return the value of magnet_db.magnet
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public String getMagnet() {
        return magnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_db.magnet
     *
     * @param magnet the value for magnet_db.magnet
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public void setMagnet(String magnet) {
        this.magnet = magnet == null ? null : magnet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_db.num
     *
     * @return the value of magnet_db.num
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_db.num
     *
     * @param num the value for magnet_db.num
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_db.types
     *
     * @return the value of magnet_db.types
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_db.types
     *
     * @param types the value for magnet_db.types
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_db.date
     *
     * @return the value of magnet_db.date
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_db.date
     *
     * @param date the value for magnet_db.date
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}