package com.play.mapper;

import com.play.entity.magnet_model;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;
@Mapper
public interface magnet_actressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table magnet_db
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     *
     *
     */
    List<String> selectForAllActressInMysql();

    List<String> selectNumByActress(String actress);

    List<String> selectActressByNum(String num);
    List<String> selectActressByNums(List<String> nums);

    List<String> selectNumInDB();





}