server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/magnet?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: moshoushijie1996
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  profiles:
    active: es,main,service

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: cn.itcast.hotel.pojo
mybatis-plus:
  mapper-locations:
    classpath: com/zhang/mapper/*.xml

