server:
  port: 8081
spring:
  datasource:
#    url: jdbc:mysql://192.168.31.113:3306/magnet?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://127.0.0.1:3306/magnet?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/,file:${myconfig.locations}
  mvc:
    static-path-pattern: /**
  web:
    cors:
      allowed-origins: "*" # 允许所有的源地址，也可以指定具体的域名
      allowed-methods: # 允许的 HTTP 方法类型
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*" # 允许所有的请求头，也可以指定具体的请求头
      allow-credentials: true # 是否允许携带凭证（cookies）
      max-age: 3600 # CORS 预检请求的有效期（秒）
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

myconfig:
  locations: D:/images/
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: cn.itcast.hotel.pojo
mybatis-plus:
  mapper-locations:
    classpath: com/zhang/mapper/*.xml


