server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/magnet?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: moshoushijie1996
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/,file:${myconfig.locations}
  mvc:
    static-path-pattern: /**
  redis:
    host: 127.0.0.1
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        max-active: 16
    jedis:
      pool:
        max-active: 16

mybatis-plus:
  mapper-locations:
    classpath: com/play/mapper/*.xml