package com.zhang.entity;

import lombok.Data;

@Data
public class PornTypes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_type2.id
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_type2.num
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_type2.types
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    private String types;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_type2.id
     *
     * @return the value of magnet_type2.id
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_type2.id
     *
     * @param id the value for magnet_type2.id
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_type2.num
     *
     * @return the value of magnet_type2.num
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_type2.num
     *
     * @param num the value for magnet_type2.num
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column magnet_type2.types
     *
     * @return the value of magnet_type2.types
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column magnet_type2.types
     *
     * @param types the value for magnet_type2.types
     *
     * @mbggenerated Tue Jan 10 22:25:41 CST 2023
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }
}