package com.zhang.entity;

import lombok.Data;

@Data
public class RequestParams {
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.actress
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String actress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.subline
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String subline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.HD
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String hd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.magnet
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String magnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.num
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.types
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column magnet_db.date
     *
     * @mbggenerated Tue Nov 22 22:22:18 CST 2022
     */
    private String date;
}
