server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://124.71.239.157:3306/magnet?useSSL=false
    username: root
    password: root960902
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: cn.itcast.hotel.pojo
mybatis-plus:
  mapper-locations:
    classpath: com/zhang/mapper/*.xml
